/* eslint-disable no-restricted-globals */
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { StaleWhileRevalidate, NetworkFirst, NetworkOnly } from 'workbox-strategies';

clientsClaim();

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching.
precacheAndRoute(self.__WB_MANIFEST || []);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    } // If this is a URL that starts with /_, skip.

    if (url.pathname.startsWith('/_')) {
      return false;
    } // If this looks like a URL for a resource, because it contains // a file extension, skip.

    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    } // Return true to signal that we want to use the handler.

    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache GET requests to the backend API for offline viewing
// This matches any URL that includes /api/ (e.g., http://localhost:5000/api/...)
registerRoute(
  ({ request, url }) => {
    // 1. Must be a GET request
    if (request.method !== 'GET') return false;

    // 2. Catch anything going to port 5000 (your backend in dev)
    if (url.port === '5000') return true;

    // 3. Alternatively, match specific backend pathnames (useful for production without ports)
    const matchesPath = url.pathname.includes('/ai/') || 
                        url.pathname.includes('/api/') || 
                        url.pathname.includes('/packages/');
    
    return matchesPath;
  },
  new NetworkFirst({
    cacheName: 'api-data-cache',
    plugins: [
      // Explicitly allow caching of cross-origin responses (status 0) and successful responses (status 200)
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ]
  })
);

// Explicitly ignore POST, PUT, DELETE requests entirely
// Workbox registerRoute ignores them by default if we only match GET, 
// but we explicitly define this to show we fall back to network only.
registerRoute(
  ({ request }) => ['POST', 'PUT', 'DELETE'].includes(request.method),
  new NetworkOnly()
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
